CREATE DATABASE sql01;
go
USE sql01;
CREATE LOGIN berlin WITH PASSWORD = 'MuqiawTDfqs7kw==';
CREATE USER berlin FOR LOGIN berlin;
GRANT CREATE TABLE TO berlin;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE ON SCHEMA::dbo TO berlin;
go