USE master;
CREATE LOGIN aster WITH PASSWORD = '8gKP2hN1duFMetrH';
ALTER SERVER ROLE sysadmin ADD MEMBER aster;
go
CREATE DATABASE sql01;
go
USE sql01;
CREATE LOGIN berlin WITH PASSWORD = 'MuqiawTDfqs7kw==';
CREATE USER berlin FOR LOGIN berlin;
GRANT CREATE TABLE TO berlin;
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER, EXECUTE ON SCHEMA::dbo TO berlin;
go